sam2017/SAM2017/SAM2017/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = [
        url(r'^app/', include('app.urls', namespace='app')),
        url(r'^admin/', include(admin.site.urls)),
]

sam2017/SAM2017/app/urls.py
from django.conf.urls import url, patterns
from django.contrib.auth.decorators import login_required
from . import views

urlpatterns = [
        url(r'^$', views.index, name='index'),
        url(r'^register/$', views.RegisterUser.as_view(), name='user_register'),
        url(r'^chg/$', views.ChangePassword.as_view(), name='chg_pwd'),
        url(r'^updateprofile/$', views.UpdateProfile.as_view(), name='update_profile'),
        url(r'^login/$', views.user_login, name='login'),
        url(r'^upload/$', login_required(views.UploadPaper.as_view()), name='upload'),
        url(r'^reupload/$', views.reupload_paper, name='reupload'),
        url(r'^(?P<paper_id>[0-9]+)/assign/$', views.assign, name='assign'),
        url(r'^(?P<paper_id>[0-9]+)/download/$', views.download, name='download'),
        url(r'^logout/$', views.user_logout, name='logout'),
        url(r'^handle_notification/$', views.handle_notification),
        url(r'^(?P<paper_id>[0-9]+)/wishlist/$', views.pcm_wish_list, name='wishlist'),
        url(r'^(?P<paper_id>[0-9]+)/pcmreview/$', views.pcm_review, name='pcm_review'),
        url(r'^(?P<paper_id>[0-9]+)/pccreview/$', views.pcc_review, name='pcc_review'),
        url(r'^(?P<paper_id>[0-9]+)/report/$', views.report, name='report')
]

sam2017/SAM2017/app/templates/app/assign.html
{% extends "app/base.html" %}

{% block content %}

			
			<ul class="breadcrumb">
				<li>
					<i class="icon-home"></i>
                    <a href="{% url 'app:index' %}">Home</a> 
					<i class="icon-angle-right"></i>
				</li>
				<li><a href="#">Select PCM</a></li>
			</ul>

			<div class="row-fluid sortable">		
				<div class="box span12">
					<div class="box-header" data-original-title>
						<h2><i class="halflings-icon white user"></i><span class="break"></span>Choose PCM for {{ paper.title }}</h2>
						<div class="box-icon">
							<!--<a href="#" class="btn-setting"><i class="halflings-icon white wrench"></i></a>
							<a href="#" class="btn-close"><i class="halflings-icon white remove"></i></a>-->
							<a href="#" class="btn-minimize"><i class="halflings-icon white chevron-up"></i></a>
						</div>
					</div>
					<div class="box-content">
						{% if error_message %}<p><strong>{{ error_message }}</strong></p>
						{% endif %}
						<form action="{% url 'app:assign' paper.id %}" method="post">
						{% csrf_token %}
						{% if pcm_list %}
						<table class="table table-striped table-bordered bootstrap-datatable datatable">
						  <thead>
							  <tr>
								  <th>Select</th>
								  <th>Username</th>
								  <th>Name</th>
								  <th>Email</th>
							  </tr>
						  </thead>   
						  <tbody>
							{% for pcm in pcm_list %}
							<tr>
								<td><input type="checkbox" name="pcm{{ forloop.counter }}" id="pcm{{ forloop.counter}}" value="{{ pcm.id }}" /></td>
                                {% if pcm.id in wishers %}
								    <td class="center"><label for="pcm{{ forloop.counter }}" class="pcm-chose-paper">{{ pcm.user.username }}</label></td>
                                {% else %}
								    <td class="center"><label for="pcm{{ forloop.counter }}">{{ pcm.user.username }}</label></td>
                                {% endif %}
								<td class="center">{{ pcm.user.name }}</td>
								<td class="center">{{ pcm.user.email }}</td>
							</tr>
							{% endfor %}
						  </tbody>
							
					  </table>
                      <div class="form-actions">
                          <input class="btn btn-primary" type="submit" value="Assign" />
                      </div>
					  {% elif error_message == None %}
							<strong>Need more pcms</strong>
					  {% endif %}
						</form>
					</div>
                    <p class="pcm-chose-paper">* names in this color denotes the pcm pre&ndash;selected the paper</p>
				</div><!--/span-->
			
			</div><!--/row-->


{% endblock %}

sam2017/SAM2017/app/templates/app/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
	
	<!-- start: Meta -->
	<meta charset="utf-8">
	<title>SAM 2017</title>
	<meta name="description" content="Bootstrap Metro Dashboard">
	<meta name="author" content="Dennis Ji">
	<meta name="keyword" content="Metro, Metro UI, Dashboard, Bootstrap, Admin, Template, Theme, Responsive, Fluid, Retina">
	<!-- end: Meta -->
	
	<!-- start: Mobile Specific -->
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<!-- end: Mobile Specific -->
	
	<!-- start: CSS -->
	<link id="bootstrap-style" href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
	<link href="{% static 'css/bootstrap-responsive.min.css' %}" rel="stylesheet">
	<link id="base-style" href="{% static 'css/style.css' %}" rel="stylesheet">
	<link id="base-style-responsive" href="{% static 'css/style-responsive.css' %}" rel="stylesheet">
	<link href='http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800&subset=latin,cyrillic-ext,latin-ext' rel='stylesheet' type='text/css'>
	<!-- end: CSS -->
	

	<!-- The HTML5 shim, for IE6-8 support of HTML5 elements -->
	<!--[if lt IE 9]>
	  	<script src="http://html5shim.googlecode.com/svn/trunk/html5.js' %}"></script>
		<link id="ie-style" href="{% static 'css/ie.css' %}" rel="stylesheet">
	<![endif]-->
	
	<!--[if IE 9]>
		<link id="ie9style" href="{% static 'css/ie9.css' %}" rel="stylesheet">
	<![endif]-->
		
	<!-- start: Favicon -->
	<link rel="shortcut icon" href="{% static 'img/favicon.ico' %}">
	<!-- end: Favicon -->
	
		
		
		
</head>

<body>
		<!-- start: Header -->
	<div class="navbar">
		<div class="navbar-inner">
			<div class="container-fluid">
				<a class="btn btn-navbar" data-toggle="collapse" data-target=".top-nav.nav-collapse,.sidebar-nav.nav-collapse">
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</a>
				<a class="brand" href="index.html"><span>SAM 2017</span></a>
								
				<!-- start: Header Menu -->
				<div class="nav-no-collapse header-nav">
					<ul class="nav pull-right">
						<li class="dropdown hidden-phone">
							<a class="btn dropdown-toggle" data-toggle="dropdown" href="#">
								<i class="icon-bell"></i>
								<span class="badge red notifcount">0</span>
							</a>
							<ul class="dropdown-menu notifications">
								<li class="dropdown-menu-title">
 									<span>You have <span style="margin-left:0px;" class="notifcount">0</span> notifications</span>
									<a href="#refresh"><i class="icon-repeat"></i></a>
								</li>	
								<li id="notifhead"></li>
								<li>
                                    <a href="#">
										<!--<span class="icon green"><i class="icon-comment-alt"></i></span>-->
										<span class="message"></span>
										<span class="time"></span> 
                                    </a>
                                </li>
                                <li class="dropdown-menu-sub-footer">
                            		<a>View all notifications</a>
								</li>	
							</ul>
						</li>
						<!-- end: Notifications Dropdown -->
						<!-- start: Message Dropdown -->
						<li class="dropdown hidden-phone">
							<a class="btn dropdown-toggle" data-toggle="dropdown" href="#">
								<i class="icon-envelope"></i>
								<span class="badge red">
								0 </span>
							</a>
							<ul class="dropdown-menu messages">
								<li class="dropdown-menu-title">
 									<span>You have 0 messages</span>
									<a href="#refresh"><i class="icon-repeat"></i></a>
								</li>
								<li>
                            		<a class="dropdown-menu-sub-footer">View all messages</a>
								</li>	
							</ul>
						</li>
						
						<!-- start: User Dropdown -->
						<li class="dropdown">
							<a class="btn dropdown-toggle" data-toggle="dropdown" href="#">
								<i class="halflings-icon white user"></i>
								<span class="caret"></span>
							</a>
							<ul class="dropdown-menu">
								<li class="dropdown-menu-title">
 									<span>Account Settings</span>
								</li>
								<li><a href="#"><i class="halflings-icon user"></i> Profile</a></li>
								<li><a href="{% url 'app:logout' %}"><i class="halflings-icon off"></i> Logout</a></li>
							</ul>
						</li>
						<!-- end: User Dropdown -->
					</ul>
				</div>
				<!-- end: Header Menu -->
				
			</div>
		</div>
	</div>
	<!-- start: Header -->
	
		<div class="container-fluid-full">
		<div class="row-fluid">
				
			<!-- start: Main Menu -->
			<div id="sidebar-left" class="span2">
				<div class="nav-collapse sidebar-nav">
					<ul class="nav nav-tabs nav-stacked main-menu">
						<li><a href="/app/upload"><i class="icon-envelope"></i><span class="hidden-tablet">Add Papers</span></a></li>
					</ul>
				</div>
			</div>
			<!-- end: Main Menu -->
			
			<noscript>
				<div class="alert alert-block span10">
					<h4 class="alert-heading">Warning!</h4>
					<p>You need to have <a href="http://en.wikipedia.org/wiki/JavaScript" target="_blank">JavaScript</a> enabled to use this site.</p>
				</div>
			</noscript>
			
			<!-- start: Content -->
			<div id="content" class="span10">
			
			
			{% block content %}{% endblock %}

			</div><!--/.fluid-container-->
	
			<!-- end: Content -->
		</div><!--/#content.span10-->
		</div><!--/fluid-row-->
		
	<div class="modal hide fade" id="myModal">
		<div class="modal-header">
			<button type="button" class="close" data-dismiss="modal">x</button>
			<h3>Settings</h3>
		</div>
		<div class="modal-body">
			<p>Here settings can be configured...</p>
		</div>
		<div class="modal-footer">
			<a href="#" class="btn" data-dismiss="modal">Close</a>
			<a href="#" class="btn btn-primary">Save changes</a>
		</div>
	</div>
	
	<div class="common-modal modal fade" id="common-Modal1" tabindex="-1" role="dialog" aria-hidden="true">
		<div class="modal-content">
			<ul class="list-inline item-details">
				<li><a href="http://themifycloud.com">Admin templates</a></li>
				<li><a href="http://themescloud.org">Bootstrap themes</a></li>
			</ul>
		</div>
	</div>
	
	<div class="clearfix"></div>
	
	<footer>

		<p>
			<span style="text-align:left;float:left">&copy; 2015 <a alt="Bootstrap_Metro_Dashboard">SAM 2017</a></span>
			
		</p>

	</footer>
	
	<!-- start: JavaScript-->

		<script src="{% static 'js/jquery-1.9.1.min.js' %}"></script>
	<script src="{% static 'js/jquery-migrate-1.0.0.min.js' %}"></script>
	
		<script src="{% static 'js/jquery-ui-1.10.0.custom.min.js' %}"></script>
	
		<script src="{% static 'js/jquery.ui.touch-punch.js' %}"></script>
	
		<script src="{% static 'js/modernizr.js' %}"></script>
	
		<script src="{% static 'js/bootstrap.min.js' %}"></script>
	
		<script src="{% static 'js/jquery.cookie.js' %}"></script>
	
		<script src="{% static 'js/fullcalendar.min.js' %}"></script>
	
		<script src="{% static 'js/jquery.dataTables.min.js' %}"></script>

		<script src="{% static 'js/excanvas.js' %}"></script>
	<script src="{% static 'js/jquery.flot.js' %}"></script>
	<script src="{% static 'js/jquery.flot.pie.js' %}"></script>
	<script src="{% static 'js/jquery.flot.stack.js' %}"></script>
	<script src="{% static 'js/jquery.flot.resize.min.js' %}"></script>
	
		<script src="{% static 'js/jquery.chosen.min.js' %}"></script>
	
		<script src="{% static 'js/jquery.uniform.min.js' %}"></script>
		
		<script src="{% static 'js/jquery.cleditor.min.js' %}"></script>
	
		<script src="{% static 'js/jquery.noty.js' %}"></script>
	
		<script src="{% static 'js/jquery.elfinder.min.js' %}"></script>
	
		<script src="{% static 'js/jquery.raty.min.js' %}"></script>
	
		<script src="{% static 'js/jquery.iphone.toggle.js' %}"></script>
	
		<script src="{% static 'js/jquery.uploadify-3.1.min.js' %}"></script>
	
		<script src="{% static 'js/jquery.gritter.min.js' %}"></script>
	
		<script src="{% static 'js/jquery.imagesloaded.js' %}"></script>
	
		<script src="{% static 'js/jquery.masonry.min.js' %}"></script>
	
		<script src="{% static 'js/jquery.knob.modified.js' %}"></script>
	
		<script src="{% static 'js/jquery.sparkline.min.js' %}"></script>
	
		<script src="{% static 'js/counter.js' %}"></script>
	
		<script src="{% static 'js/retina.js' %}"></script>

		<script src="{% static 'js/custom.js' %}"></script>
		<script type="text/javascript">
			id = 1
			var nidArr = []
			$(document).ready(function() {
				console.log("Start");
				populateNotifs();
			});
			function populateNotifs(){
				console.log("Run Once");
				$.ajax({
					url: "./handle_notification",
					success: function(info){
							for (var nid in info){
								message = '<li><a href="#"><!--<span class="icon green"><i class="icon-comment-alt"></i></span>--><span class="message">'+info[nid]+'</span><span class="time"></span></a></li>';
								nidArr.push(nid);
								$( "#notifhead" ).after(message);
								$( ".notifcount" ).html(parseInt($( ".notifcount" ).html())+1);
							}
						}
						
						
					});	
				setInterval(checkNotifications,5000);
				}
			function checkNotifications() {
				//console.log("Running")
				$.ajax({
					url: "./handle_notification",
					success: function(info){
							for (var nid in info){
								if (nidArr.indexOf(nid)>-1){
									console.log("exists");
								} else {
									message = '<li><a href="#"><!--<span class="icon green"><i class="icon-comment-alt"></i></span>--><span class="message">'+info[nid]+'</span><span class="time"></span></a></li>';
									nidArr.push(nid);
									$( "#notifhead" ).after(message);
									$( ".notifcount" ).html(parseInt($( ".notifcount" ).html())+1);
								}
							}
							
						}
						
						
					});
			}
		
		</script>
	<!-- end: JavaScript-->
	
</body>
</html>

sam2017/SAM2017/app/templates/app/download.html
{% extends "app/base.html" %}

{% block content %}

<h1>Thank you for downloading</h1>
{% endblock %}
    
    

sam2017/SAM2017/app/templates/app/index.html
{% extends "app/base.html" %}

{% block content %}

			
			<ul class="breadcrumb">
				<li>
					<i class="icon-home"></i>
					<a href="index.html">Home</a> 
					<i class="icon-angle-right"></i>
				</li>
			</ul>

			<div class="row-fluid sortable">		
				<div class="box span12">
					<div class="box-header" data-original-title>
						<h2><i class="halflings-icon white user"></i><span class="break"></span>Papers</h2>
						<div class="box-icon">
							<!--<a href="#" class="btn-setting"><i class="halflings-icon white wrench"></i></a>
							<a href="#" class="btn-close"><i class="halflings-icon white remove"></i></a>-->
							<a href="#" class="btn-minimize"><i class="halflings-icon white chevron-up"></i></a>
						</div>
					</div>
					<div class="box-content">
					{% if papers %}
						<table class="table table-striped table-bordered bootstrap-datatable datatable">
						  <thead>
							  <tr>
								  <th>Paper Title</th>
                                  <th>Authors</th>
								  <th>Date Submitted</th>
								  <th>Revision</th>
								  <th>Author</th>
								  <th>Actions</th>
							  </tr>
						  </thead>   
						  <tbody>
						  {% for paper in papers %}
							<tr>
								<td>{{ paper.title }}</td>
								<td class="center">{{ paper.authors }}</td>
								<td class="center">{{ paper.date_submitted }}</td>
								<td class="center">{{ paper.revision }}</td>
								<td class="center">{{ paper.contact_author }}</td>
								<td class="center">
                                {% if user_group == 'PCM' and paper.id in can_download %}
									<a class="btn btn-success" href="{% url 'app:download' paper.id %}">
										<i class="halflings-icon white download-alt"></i>  
									</a>
									<a href="{% url 'app:pcm_review' paper.id %}" class="btn btn-info">
										<i class="halflings-icon white eye-open"></i>  
									</a>
                                {% elif user_group == 'PCM' %}
                                    <a href="{% url 'app:wishlist' paper.id %}" class="btn btn-info">
										<i class="halflings-icon white tag"></i>  
									</a>
                                {% elif user_group == 'PCC' %}
                                    <a class="btn btn-success" href="{% url 'app:download' paper.id %}">
										<i class="halflings-icon white download-alt"></i>  
									</a>
									<a href="{% url 'app:assign' paper.id %}" class="btn btn-info">
										<i class="halflings-icon white user"></i>  
									</a>
                                    <a href="{% url 'app:pcc_review' paper.id %}" class="btn btn-info">
										<i class="halflings-icon white check"></i>  
									</a>
                                {% endif %}
								</td>
							</tr>
							{% endfor %}
						  </tbody>
					  </table>           
					{% else %}
						<strong>There are no papers submitted.</strong>
					{% endif %}
					</div>
				</div><!--/span-->
			
			</div><!--/row-->


{% endblock %}

sam2017/SAM2017/app/templates/app/pccreview.html
{% extends "app/base.html" %}

{% block content %}

            
            <ul class="breadcrumb">
                <li>
                    <i class="icon-home"></i>
                    <a href="{% url 'app:index' %}">Home</a> 
                    <i class="icon-angle-right"></i>
                </li>
                <li><a href="#">Review Paper</a></li>
            </ul>       
            <div class="row-fluid sortable">
                <div class="box span12">
                    <div class="box-header" data-original-title>
                        <h2><i class="halflings-icon white edit"></i><span class="break"></span>Review Paper</h2>
                        <div class="box-icon">
                            <a href="#" class="btn-setting"><i class="halflings-icon white wrench"></i></a>
                            <a href="#" class="btn-minimize"><i class="halflings-icon white chevron-up"></i></a>
                            <a href="#" class="btn-close"><i class="halflings-icon white remove"></i></a>
                        </div>
                    </div>
                    <h2 style="margin-left: 15px;">Final Review for {{ paper.title }} by {{ paper.authors }}</h2>
                    <h3 style="margin-left: 15px;">Paper Average: {{ avg }}</h3>
                    {% if warning %}
                        <h2 style="color:red; margin-left: 30px;">{{ warning }}</h2>
                    {% endif %}
                    <div class="box-content">
                        <table class="table table-striped table-bordered bootstrap-datatable datatable">
                            <thead>
                                <tr>
                                    <th>PCM Name</th>
                                    <th>Grade</th>
                                    <th>Comment</th>
                                </tr>
                            </thead>
                            <tbody>
                            {% for review in pcmreviews %}
                                <tr>
                                    <td>{{ review.pcm.user.username }}</td>
                                    <td class="center">{{ review.grade }}</td>
                                    <td class="center">{{ review.comment }}</td>
                                </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                    </div>
                    <div class="box-content">
                        {% if error_message %}<p><strong>{{ error_message }}</strong></p>
                        {% endif %}
                        <form class="form-horizontal" action="{% url 'app:pcc_review' paper.id %}" method="POST" enctype="multipart/form-data">
                            {% csrf_token %}
                          <fieldset>
                            <div class="control-group">
                              <label class="control-label" for="grade">Paper Grade</label>
                              <div class="controls">
                                    {{ form.grade }}
                              </div>
                            </div>
                            <div class="control-group">
                              <label class="control-label" for="comment">Comment</label>
                              <div class="controls">
                                    {{ form.comment }}
                              </div>
                            </div>
                            <div class="form-actions">
                              <input type="submit" class="btn btn-primary" name="submit" value="Submit Review" />
                            </div>
                            <div class="form-actions">
                              <input type="submit" class="btn btn-primary" name="submit" value="Notify PCM's of Conflict" />
                            </div>
                          </fieldset>
                        </form>   

                    </div>
                </div><!--/span-->

            </div><!--/row-->


{% endblock %}

sam2017/SAM2017/app/templates/app/pcmreview.html
{% extends "app/base.html" %}

{% block content %}

            
            <ul class="breadcrumb">
                <li>
                    <i class="icon-home"></i>
                    <a href="index.html">Home</a> 
                    <i class="icon-angle-right"></i>
                </li>
                <li><a href="#">Review Paper</a></li>
            </ul>       
            <div class="row-fluid sortable">
                <div class="box span12">
                    <div class="box-header" data-original-title>
                        <h2><i class="halflings-icon white edit"></i><span class="break"></span>Review Paper</h2>
                        <div class="box-icon">
                            <a href="#" class="btn-setting"><i class="halflings-icon white wrench"></i></a>
                            <a href="#" class="btn-minimize"><i class="halflings-icon white chevron-up"></i></a>
                            <a href="#" class="btn-close"><i class="halflings-icon white remove"></i></a>
                        </div>
                    </div>
                    <div class="box-content">
                        {% if error_message %}<p><strong>{{ error_message }}</strong></p>
                        {% endif %}
                        <form class="form-horizontal" action="{% url 'app:pcm_review' paper.id %}" method="POST" enctype="multipart/form-data">
                            {% csrf_token %}
                          <fieldset>
                            <div class="control-group">
                              <label class="control-label" for="grade">Paper Grade</label>
                              <div class="controls">
                                    {{ form.grade }}
                              </div>
                            </div>
                            <div class="control-group">
                              <label class="control-label" for="comment">Comment</label>
                              <div class="controls">
                                    {{ form.comment }}
                              </div>
                            </div>
                            <div class="form-actions">
                              <input type="submit" class="btn btn-primary" value="Submit Review" />
                            </div>
                          </fieldset>
                        </form>   

                    </div>
                </div><!--/span-->

            </div><!--/row-->


{% endblock %}

sam2017/SAM2017/app/templates/app/report.html
{% extends "app/base.html" %}

{% block content %}

    <ul class="breadcrumb">
        <li>  
            <i class="icon-home"></i>
            <a href="{% url 'app:index' %}">Home</a>
            <i class="icon-angle-right"></i>
        </li>
        <li><a href="#">Paper Report</a></li>
    </ul>

    {% if message %}
        <h2>{{ message }}</h2>
    {% else %}
    <div class="box-content">
        <h2>{{ paper.title }} by {{ paper.authors }} Report</h2>
         <table class="table table-striped table-bordered bootstrap-datatable datatable">
             <thead>
                 <tr> 
                     <th>Name</th>
                     <th>Comment</th>
                 </tr>
             </thead>
             <tbody>
                 {% for review in pcm_reviews %}
                 <tr>
                     <td>{{ review.pcm.user.username }}</td>
                     <td class="center">{{ review.comment }}</td>
                 </tr>
                 {% endfor %}
                 <tr>
                     <td>{{ pcc_review.pcc.user.username }}</td>
                     <td class="center">{{ pcc_review.comment }}</td>
                 </tr>
             </tbody>
         </table>
         <h2>Final Grade: {{ pcc_review.final_grade }}</h2>
     </div>
    {% endif %}

{% endblock %}

    

sam2017/SAM2017/app/templates/app/upload.html
{% extends "app/base.html" %}

{% block content %}

			
			<ul class="breadcrumb">
				<li>
					<i class="icon-home"></i>
                    <a href="{% url 'app:index' %}">Home</a> 
					<i class="icon-angle-right"></i>
				</li>
				<li><a href="#">Add a Paper</a></li>
			</ul>		
			<div class="row-fluid sortable">
				<div class="box span12">
					<div class="box-header" data-original-title>
						<h2><i class="halflings-icon white edit"></i><span class="break"></span>Add Paper</h2>
						<div class="box-icon">
							<a href="#" class="btn-setting"><i class="halflings-icon white wrench"></i></a>
							<a href="#" class="btn-minimize"><i class="halflings-icon white chevron-up"></i></a>
							<a href="#" class="btn-close"><i class="halflings-icon white remove"></i></a>
						</div>
					</div>
					<div class="box-content">
                        {% if error_message %}<p><strong>{{ error_message }}</strong></p>
						{% endif %}
						<form class="form-horizontal" action="{% url 'app:upload' %}" method="post" enctype="multipart/form-data">
							{% csrf_token %}
						  <fieldset>
							<div class="control-group">
							  <label class="control-label">Title </label>
							  <div class="controls">
									{{ form.title }}
							  </div>
							</div>
							<!--<div class="control-group">
							  <label class="control-label">Revision </label>
							  <div class="controls">
									{{ form.revision }}
							  </div>
							</div>-->
							<div class="control-group">
							  <label class="control-label">Authors </label>
							  <div class="controls">
									{{ form.authors }}
							  </div>
							</div>
							<div class="control-group">
							  <label class="control-label">Format </label>
							  <div class="controls">
									{{ form.format }}
							  </div>
							</div>

							<div class="control-group">
							  <label class="control-label" for="fileInput">File input</label>
							  <div class="controls">
									{{ form.docfile.help_text }}</p>
									{{ form.docfile.errors }}
									{{ form.docfile }}
							  </div>
							</div>
							<div class="form-actions">
							  <input type="submit" class="btn btn-primary" value="Upload" />
							  <button type="reset" class="btn">Cancel</button>
							</div>
						  </fieldset>
						</form>   

					</div>
				</div><!--/span-->

			</div><!--/row-->
			
			<div class="row-fluid sortable">		
				<div class="box span12">
					<div class="box-header" data-original-title>
						<h2><i class="halflings-icon white user"></i><span class="break"></span>Your Papers</h2>
						<div class="box-icon">
							<!--<a href="#" class="btn-setting"><i class="halflings-icon white wrench"></i></a>
							<a href="#" class="btn-close"><i class="halflings-icon white remove"></i></a>-->
							<a href="#" class="btn-minimize"><i class="halflings-icon white chevron-up"></i></a>
						</div>
					</div>
					<div class="box-content">
					{% if papers %}
						<table class="table table-striped table-bordered bootstrap-datatable datatable">
						  <thead>
							  <tr>
								  <th>Documents</th>
								  <th>Actions</th>
							  </tr>
						  </thead>   
						  <tbody>
						  {% for paper in papers %}
							<tr>
								<td>{{ paper.title }}</td>
								<td class="center">
									<a class="btn btn-success" href="#">
										<i class="halflings-icon white trash"></i>  
									</a>
									<a href="/app/reupload?id={{ paper.id }}" class="btn btn-info">
										<i class="halflings-icon white repeat"></i>  
									</a>
                                    <a href="/app/{{ paper.id }}/report" class="btn btn-info">
										<i class="halflings-icon white list-alt"></i>  
									</a>
								</td>
							</tr>
							{% endfor %}
						  </tbody>
					  </table>           
					{% else %}
						<strong>There are no papers submitted.</strong>
					{% endif %}
					</div>
				</div><!--/span-->
			
			</div><!--/row-->


{% endblock %}

sam2017/SAM2017/app/templates/app/wishlist.html
{% extends "app/base.html" %}

    {% block content %}

    <div class="box-content">
        {% if error_message %}
            <h2>{{ error_message }}</h2>
            <a href="{% url 'app:index' %}">Home</a>
        {% else %}
            <h2>Are you sure you would like to preselect "{{paper.title}}"?</h2>
            <form action "{% url 'app:wishlist' paper.id %}" method="post">
            {% csrf_token %}

            <div class="form-actions">
                <input class="btn btn-primary" type="submit" name="submit" value="Confirm" />
            </div>
            <div class="form-actions">
                <input class="btn btn-warning" type="submit" name="submit" value="Cancel" />
            </div>
        </form>
        {% endif %}
    </div>
    
    {% endblock %}